include:
  - project: 'r/ci-cd-fragments'
    file: '/msbuild.yml'
  - project: 'r/ci-cd-fragments'
    file: '/nunit3.yml'
  - project: 'r/ci-cd-fragments'
    file: '/nuget.yml'

stages:
  - build
  - test
  - pack
  - deploy
  
variables:
  VERSION: 0.2.$CI_PIPELINE_IID

build:
  extends: .msbuild
  stage: build

test:
  extends: .nunit3
  stage: test
  variables:
    TEST_ASSEMBLY_PATTERN: bin\\.*Tests?\.dll$

pack:
  extends: .nuget-pack
  stage: pack
  variables:
    SPEC_FILE: ServiceMapper/ServiceMapper.csproj

deploy:
  extends: .nuget-push
  stage: deploy
  only: [master, /^release\//]
  variables:
    SOURCE: $PROGET_UTILITIES_ADDRESS
    API_KEY: $PROGET_API_KEY
