variables:
  PROJECT: ServiceMapper/ServiceMapper.csproj

stages:
  - build
  - deploy

build:
  stage: build
  tags: [msbuild, nuget]
  script:
    - >-
      &$NUGET "restore $($NUGET_SOURCES -replace "(.+)([\r\n]+|`$)","-Source `$1 ")".split()
    - >-
      &$MSBUILD /t:Rebuild /property:Configuration=Release
    - >-
      &$NUGET pack "$PROJECT" -OutputDirectory bin -Version 0.2.$CI_PIPELINE_IID -Properties Configuration=Release
  artifacts:
    paths:
      - 'bin\*.nupkg'

deploy:
  stage: deploy
  only: [master]
  tags: [nuget]
  script: >-
    &$NUGET push bin\*.nupkg "$PROGET_API_KEY" -Source "$PROGET_UTILITIES_ADDRESS"
